const products = [
  // 👔 Mens Wear
  {
    id: 1,
    name: "Men's Classic Shirt",
    description: "Cotton blend, slim fit shirt.",
    price: 1299,
    category: "Mens Wear",
    brand: "Raymond",
    image: "/Photos/image1.jpeg",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Men's Casual Jeans",
    description: "Blue washed denim jeans.",
    price: 1699,
    category: "Mens Wear",
    brand: "Levis",
    image: "/Photos/image2.jpeg",
    rating: 4.2,
  },
  {
    id: 3,
    name: "Men's Formal Trousers",
    description: "Slim fit formal office trousers.",
    price: 1999,
    category: "Mens Wear",
    brand: "Peter England",
    image: "/Photos/image3.webp",
    rating: 4.0,
  },
  {
    id: 4,
    name: "Men's Blazer",
    description: "Navy blue formal blazer.",
    price: 2999,
    category: "Mens Wear",
    brand: "Arrow",
    image: "/Photos/image4.webp",
    rating: 4.4,
  },
  {
    id: 5,
    name: "Men's Sweatshirt",
    description: "Comfortable cotton sweatshirt.",
    price: 1199,
    category: "Mens Wear",
    brand: "H&M",
    image: "/Photos/image5.jpeg",
    rating: 4.3,
  },
  {
    id: 6,
    name: "Men's Hoodie",
    description: "Casual full-sleeve hoodie.",
    price: 1399,
    category: "Mens Wear",
    brand: "Nike",
    image: "/Photos/image6.jpeg",
    rating: 4.5,
  },
  {
    id: 7,
    name: "Men's Track Pants",
    description: "Black slim-fit track pants.",
    price: 999,
    category: "Mens Wear",
    brand: "Adidas",
    image: "/Photos/image7.jpeg",
    rating: 4.1,
  },
  {
    id: 8,
    name: "Men's Polo T-Shirt",
    description: "Cotton half-sleeve polo.",
    price: 799,
    category: "Mens Wear",
    brand: "U.S. Polo",
    image: "/Photos/image8.jpeg",
    rating: 4.0,
  },
  {
    id: 9,
    name: "Men's Cargo Pants",
    description: "Army-style cargo pants.",
    price: 1499,
    category: "Mens Wear",
    brand: "Wrangler",
    image: "/Photos/image9.jpeg",
    rating: 4.2,
  },
  {
    id: 10,
    name: "Men's Leather Jacket",
    description: "Black faux leather biker jacket.",
    price: 2499,
    category: "Mens Wear",
    brand: "Roadster",
    image: "/Photos/image10.jpeg",
    rating: 4.6,
  },

  // 👗 Womens Wear
  {
    id: 11,
    name: "Women's Summer Dress",
    description: "Floral printed knee-length dress.",
    price: 1499,
    category: "Womens Wear",
    brand: "Zara",
    image: "/Photos/image11.png",
    rating: 4.3,
  },
  {
    id: 12,
    name: "Women's Kurti",
    description: "Cotton ethnic Kurti with embroidery.",
    price: 899,
    category: "Womens Wear",
    brand: "Biba",
    image: "/Photos/image12.jpg",
    rating: 4.6,
  },
  {
    id: 13,
    name: "Women's Jeans",
    description: "Skinny stretchable denim jeans.",
    price: 1699,
    category: "Womens Wear",
    brand: "Pepe Jeans",
    image: "/Photos/image13.jpeg",
    rating: 4.2,
  },
  {
    id: 14,
    name: "Women's Leggings",
    description: "Pack of 2 cotton leggings.",
    price: 599,
    category: "Womens Wear",
    brand: "Go Colors",
    image: "/Photos/image14.jpeg",
    rating: 4.1,
  },
  {
    id: 15,
    name: "Women's Blouse",
    description: "Printed silk blouse.",
    price: 799,
    category: "Womens Wear",
    brand: "Global Desi",
    image: "/Photos/image15.avif",
    rating: 4.0,
  },
  {
    id: 16,
    name: "Women's Gown",
    description: "Long maxi gown with dupatta.",
    price: 2299,
    category: "Womens Wear",
    brand: "Soch",
    image: "/Photos/image16.webp",
    rating: 4.4,
  },
  {
    id: 17,
    name: "Women's Top",
    description: "Casual striped crop top.",
    price: 699,
    category: "Womens Wear",
    brand: "ONLY",
    image: "/Photos/image17.webp",
    rating: 4.3,
  },
  {
    id: 18,
    name: "Women's Saree",
    description: "Georgette saree with blouse piece.",
    price: 1899,
    category: "Womens Wear",
    brand: "Kalini",
    image: "/Photos/image18.webp",
    rating: 4.5,
  },
  {
    id: 19,
    name: "Women's Jacket",
    description: "Winter quilted jacket.",
    price: 1799,
    category: "Womens Wear",
    brand: "Monte Carlo",
    image: "/Photos/image19.jpeg",
    rating: 4.2,
  },
  {
    id: 20,
    name: "Women's Palazzo",
    description: "Ethnic printed palazzo pants.",
    price: 899,
    category: "Womens Wear",
    brand: "W for Woman",
    image: "/Photos/image20.jpg",
    rating: 4.3,
  },

  // 🧒 Kids Wear
  {
    id: 21,
    name: "Kids T-shirt",
    description: "Cartoon printed soft T-shirt.",
    price: 499,
    category: "Kids Wear",
    brand: "UCB Kids",
    image: "/Photos/image21.jpeg",
    rating: 4.4,
  },
  {
    id: 22,
    name: "Kids Jeans",
    description: "Stretchable jeans for kids.",
    price: 699,
    category: "Kids Wear",
    brand: "Max",
    image: "/Photos/image22.jpeg",
    rating: 4.1,
  },
  {
    id: 23,
    name: "Kids Hoodie",
    description: "Warm fleece hoodie.",
    price: 999,
    category: "Kids Wear",
    brand: "Babyhug",
    image: "/Photos/image23.jpeg",
    rating: 4.3,
  },
  {
    id: 24,
    name: "Kids Night Suit",
    description: "Cotton cartoon-printed nightwear.",
    price: 599,
    category: "Kids Wear",
    brand: "Mothercare",
    image: "/Photos/image24.jpeg",
    rating: 4.2,
  },
  {
    id: 25,
    name: "Kids Frock",
    description: "Party wear frock with bow design.",
    price: 899,
    category: "Kids Wear",
    brand: "Tiny Girl",
    image: "/Photos/image25.webp",
    rating: 4.6,
  },
  {
    id: 26,
    name: "Kids Shorts",
    description: "Pack of 3 cotton shorts.",
    price: 599,
    category: "Kids Wear",
    brand: "FirstCry",
    image: "/Photos/image26.jpeg",
    rating: 4.0,
  },
  {
    id: 27,
    name: "Kids Ethnic Wear",
    description: "Kurta pajama set for boys.",
    price: 1299,
    category: "Kids Wear",
    brand: "Little Stars",
    image: "/Photos/image27.jpg",
    rating: 4.4,
  },
  {
    id: 28,
    name: "Kids Sweater",
    description: "Woolen pullover with patterns.",
    price: 799,
    category: "Kids Wear",
    brand: "ToffyHouse",
    image: "/Photos/image28.jpeg",
    rating: 4.1,
  },
  {
    id: 29,
    name: "Kids Cap",
    description: "Winter knitted cap.",
    price: 299,
    category: "Kids Wear",
    brand: "Cherokee",
    image: "/Photos/image29.jpeg",
    rating: 4.0,
  },
  {
    id: 30,
    name: "Kids Sandals",
    description: "Comfortable anti-slip sandals.",
    price: 699,
    category: "Kids Wear",
    brand: "Crocs",
    image: "/Photos/image30.jpg",
    rating: 4.3,
  },
];

export default products;